name: CI

on:
  - pull_request
  - workflow_dispatch

# Pushing new commits to the same branch
# will cancel any previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Node Version
        id: get-node-version
        # All of this is to get the node version from package.json
        # and remove the leading and trailing quotes, otherwise it
        # breaks the github action that consumes this data
        run: echo node-version=$(cat package.json | jq ".engines.node" | sed 's/^"\(.*\)"$/\1/') >> $GITHUB_OUTPUT

    outputs:
      node-version: ${{ steps.get-node-version.outputs.node-version }}

  e2e:
    needs:
      - get-node-version
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.get-node-version.outputs.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run E2E Tests
        run: npm run e2e
